# Dockerfile.backend
FROM python:3.11-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем всё приложение
COPY . .

# Собираем статику (если будет использоваться)
RUN python manage.py collectstatic --noinput

# Запуск через Gunicorn (продакшен!)
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--timeout", "120", "app.wsgi:application"]